 GET http://localhost:3000/courses

###

GET http://localhost:3000/courses/608f56034fbc9241f004fc68

###

POST http://localhost:3000/courses
Content-Type: application/json

{
  "course": "COSC 222",
  "section": 101,
  "professor": "Senapi",
  "faculty": "Faculty of Anima LMAO",
  "location": "Room 51",
  "startDate": "May 2",
  "endDate": "Not June 2"
}

###

PATCH http://localhost:3000/courses/608f58f0e3be5b0b50497eee
Content-Type: application/json

{
  "professor": "NOOB"
}


###

GET http://localhost:8000/subjects

###

POST http://localhost:8000/subjects
Content-Type: application/json

{
  "subjectCode": "COSC",
  "subjectTitle": "Computer Science",
  "subjectFaculty": "Faculty of Arts and Sciences",
  "subjectLink": "https://courses.students.ubc.ca/cs/courseschedule?pname=subjarea&tname=subj-department&dept=COSC"
}

###

DELETE  http://localhost:8000/subjects

###

POST http://localhost:8000/api/UBCO/sections
Content-Type: application/json

{
  "section": "COSC 121 101",
  "activity": "Lecture",
  "campus": "ubco"
}

###

POST http://localhost:8000/api/UBCO/courses
Content-Type: application/json

{
  "subject": "Comp Sci",
  "course": "Comp Sci 101",
  "courseNumber": "101",
  "title": "Comp Sci",
  "faculty": "Comp Sci",
  "sections": [
    "101",
    "L01",
    "L02",
    "L03",
    "L04",
    "L05",
    "L06",
    "WL1"
  ],
  "idiot": "me",
  "link": "Comp Sci",
  "session": "Comp Sci",
  "campus": "Comp Sci"
}